version: "3.0"
services:
  db:
    container_name: "db"
    image: yandex/clickhouse-server
    restart: always
    environment:
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_DB=clickhouse
    ports:
      - "9000:9000"
    networks:
      - custom
networks:
  custom:
    driver: bridge
